In [14]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
df = pd.read_csv('sample_dataset.csv')
df = df.set_index('TID')
df # to make sure that the code imported the dataset properly

     Beer  Bread  Butter  diabers  milk  cookies
TID
1       1      0       0        1     1        0
2       0      1       1        0     1        0
3       0      0       0        1     1        1
4       0      1       1        0     0        1
5       1      0       0        1     0        1
6       0      1       1        0     1        0
7       1      1       1        1     0        1
8       1      0       0        1     0        0
9       0      1       1        1     1        1
10      1      0       0        1     1        1

In [15]:
def apriori_method(minimum_support):
    # first, we should generate the frequent itemset
    freq_itemset = apriori(df, min_support = minimum_support, use_colnames=True)
    # then, we should generate the association rules
    rules = association_rules(freq_itemset, metric='lift', min_threshold=1) # we could use eaither lift or confidence as metric
    return rules

In [24]:
apriori_method(0.3)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Beer),(diabers),0.5,0.7,0.5,1.000000,1.428571,0.15,inf
1,(diabers),(Beer),0.7,0.5,0.5,0.714286,1.428571,0.15,1.75
2,(Butter),(Bread),0.5,0.5,0.5,1.000000,2.000000,0.25,inf
3,(Bread),(Butter),0.5,0.5,0.5,1.000000,2.000000,0.25,inf
4,(cookies),(diabers),0.6,0.7,0.5,0.833333,1.190476,0.08,1.80
5,(diabers),(cookies),0.7,0.6,0.5,0.714286,1.190476,0.08,1.40

In [29]:
# we could export these rules into a csv file
apriori_method(0.3).to_csv('association_rules_0.2support.csv')